Indentation ....

diff --git a/Validation/Outils/Genere_courbe/Run b/Validation/Outils/Genere_courbe/Run
--- a/Validation/Outils/Genere_courbe/Run
+++ b/Validation/Outils/Genere_courbe/Run
@@ -87,29 +87,29 @@ if [ $run -ne -2 ]
     then
     $DIR/prepare_gen $orig || exit -1
     if [ "$NBPASMAX" != "" ] 
-	then
-	echo "We modify .data to run only on $NBPASMAX time step"
-	for jdd in `find build -name '*'.data`
-	  do
+    then
+    echo "We modify .data to run only on $NBPASMAX time step"
+    for jdd in `find build -name '*'.data`
+      do
           mv $jdd $jdd.save
-	  # comme dans copie_cas_test sans le solveur 
-	    $TRUST_Awk -v NBPASMAX=$NBPASMAX '/tinit/ {print $0;print "\tnb_pas_dt_max", NBPASMAX ;getline}\
+      # comme dans copie_cas_test sans le solveur 
+        $TRUST_Awk -v NBPASMAX=$NBPASMAX '/tinit/ {print $0;print "\tnb_pas_dt_max", NBPASMAX ;getline}\
    !/nb_pas_dt_max/ {print $0}\
 ' $jdd.save > $jdd
-	done
+    done
     fi
     # dans le cas ou on copie le cas test on verifie que le prm est identique dans src et dans build (cas des prm generes par prepare)
     if [ $run -eq -1 ]
-	then
-	modif=`diff $orig/src/*prm build/${prm}`
-	if [ "$modif" != "" ]
-	then 
-	    echo "-> Problem with $orig/src/*prm and build/${prm}" >/dev/stderr
-	    echo "-> There is a difference between the prm file in build directory and the prm file in the src directory." >/dev/stderr
-	    diff $orig/src/*prm build/${prm} >/dev/stderr
-	    mv build build_err
-	    exit -1    
-	fi
+    then
+    modif=`diff $orig/src/*prm build/${prm}`
+    if [ "$modif" != "" ]
+    then 
+        echo "-> Problem with $orig/src/*prm and build/${prm}" >/dev/stderr
+        echo "-> There is a difference between the prm file in build directory and the prm file in the src directory." >/dev/stderr
+        diff $orig/src/*prm build/${prm} >/dev/stderr
+        mv build build_err
+        exit -1    
+    fi
     fi
 else
 # $DIR/prepare_gen $orig
@@ -160,7 +160,7 @@ then
             task[$n]=$!
         else
 
-# See https://stackoverflow.com/questions/1537956/bash-limit-the-number-of-concurrent-jobs	
+# See https://stackoverflow.com/questions/1537956/bash-limit-the-number-of-concurrent-jobs    
 function max_bg_procs {
     if [[ $# -eq 0 ]] ; then
        echo "Usage: max_bg_procs NUM_PROCS.  Will wait until the number of background (&)"
@@ -176,33 +176,33 @@ function max_bg_procs {
        sleep 1
     done
 }
-	    max_bg_procs $TRUST_NB_PROCS
-	    awk -F'"' '{print $2}' $cmd
+        max_bg_procs $TRUST_NB_PROCS
+        awk -F'"' '{print $2}' $cmd
             bash ./$cmd &
             processes=$processes" "$!
             task[$n]=$!
         fi
-	let n=$n+1
+    let n=$n+1
      done
      while [ "$processes" != "" ]
      do
         for process in $processes
         do
-	   if [ "`kill -0 $process 2>/dev/null;echo $?`" != 0 ]
-	   then
-	      # Recherche du calcul qui a fini:
-	      let i=1
-	      while [ ${task[$i]} != $process ] && [ $i -lt $n ]
-	      do
-	         let i=$i+1
-	      done
-	      log=cmds$i.log
-	      task=cmds$i.sh
-	      echo "Calculation $i has finished. See $log"
-	      processes=`echo $processes | sed "1,$ s?$process??g"`
-	   fi
+       if [ "`kill -0 $process 2>/dev/null;echo $?`" != 0 ]
+       then
+          # Recherche du calcul qui a fini:
+          let i=1
+          while [ ${task[$i]} != $process ] && [ $i -lt $n ]
+          do
+             let i=$i+1
+          done
+          log=cmds$i.log
+          task=cmds$i.sh
+          echo "Calculation $i has finished. See $log"
+          processes=`echo $processes | sed "1,$ s?$process??g"`
+       fi
         done
-	sleep 1
+    sleep 1
      done
      # Lancement du post_run 
      bash ./post_run.sh
@@ -222,20 +222,20 @@ if [ $run -le -1 ]
 then
     list_tot=`python $DIR/src/genererCourbes.py -p $prm  --get_cmd_to_run=yes| grep get_total_time | sed "s/\.perf/.data/g" | sed "s/get_total_time//" | sed "s/\.\///g"  `
     if [ -f liste_cas_exclu_nr ]
-	then
-	list_cas_nr="" 
-	for cas in $list_tot
-	  do
-	  if [ "`grep $cas liste_cas_exclu_nr`" = "" ]
-	      then
-	      list_cas_nr=${list_cas_nr}" "$cas
-	  else
-	      echo not_in_nr    $cas not in nr
-	  fi
-	done
-	echo "liste_cas_nr" $list_cas_nr 
+    then
+    list_cas_nr="" 
+    for cas in $list_tot
+      do
+      if [ "`grep $cas liste_cas_exclu_nr`" = "" ]
+          then
+          list_cas_nr=${list_cas_nr}" "$cas
+      else
+          echo not_in_nr    $cas not in nr
+      fi
+    done
+    echo "liste_cas_nr" $list_cas_nr 
     else
-	echo "liste_cas_nr" $list_tot
+    echo "liste_cas_nr" $list_tot
     fi
     exit
 fi
@@ -243,14 +243,14 @@ if [ $run -ne 0 ]
 then
     if [ "`grep erreur_calcul temps_total`" != "" ]
     then 
-	echo
-	echo 
-	cat temps_total
-	echo
-	echo
-	echo "-> Error in: python $DIR/src/genererCourbes.py -p $prm $*"
-	echo "-> Search and fix all the previous errors."
-	exit 1
+    echo
+    echo 
+    cat temps_total
+    echo
+    echo
+    echo "-> Error in: python $DIR/src/genererCourbes.py -p $prm $*"
+    echo "-> Search and fix all the previous errors."
+    exit 1
     fi
 fi
 echo "=============================="
